#!/usr/bin/env python3
"""Compute word counts for skill and soul variant files.

Run this after regenerating skills/souls to get the current word counts
for updating docs/models.md. The output is a markdown table ready to paste.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

VARIANTS = [
    ("gpt-oss-120b", "linus-torvalds-skill/SKILL.md", "soul/soul.md"),
    ("glm5.2", "linus-torvalds-skill/SKILL-GLM.md", "soul/soul-glm.md"),
    ("mistral-small-4-119b", "linus-torvalds-skill/SKILL-Mistral.md", "soul/soul-mistral.md"),
]


def word_count(path: Path) -> int:
    if not path.exists():
        return 0
    return len(path.read_text(encoding="utf-8").split())


def main() -> None:
    print("<!-- Variant word counts (generated by scripts/generate_variant_table.py) -->")
    print("<!-- Run after regenerating skills/souls to update docs/models.md -->")
    print()
    print("| Model | Skill words | Soul words |")
    print("|---|---|---|")
    for model, skill_path, soul_path in VARIANTS:
        sw = word_count(ROOT / skill_path)
        sow = word_count(ROOT / soul_path)
        print(f"| {model} | {sw:,} | {sow:,} |")


if __name__ == "__main__":
    main()
